services:
  nodejs-server:
    image: strangercoding/cohort-backend
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - backend-internal

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - backend-internal

networks:
  backend-internal:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: